const fs = require('fs/promises');
const path = require('path');
const vm = require('vm');

const REPO_ROOT = path.resolve(__dirname, '..');
const DOCS_PROJECT_ROOT = path.join(REPO_ROOT, 'docs');
const DEFAULT_DOCS_HOST = 'https://docs.apiease.com';
const OUTPUT_PATH = path.join(__dirname, 'apiEaseDocsConsolidated.md');

function normalizeUrlPath(...parts) {
  const cleaned = parts
    .filter(Boolean)
    .map((part) => part.replace(/^\/+|\/+$/g, ''))
    .filter((part) => part.length > 0);

  return `/${cleaned.join('/')}`;
}

function parseFrontMatter(raw) {
  if (!raw.startsWith('---')) {
    return {frontMatter: {}, body: raw};
  }

  const match = raw.match(/^---\n([\s\S]*?)\n---\n?/);
  if (!match) {
    return {frontMatter: {}, body: raw};
  }

  const frontMatter = {};
  const lines = match[1].split('\n');

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const kv = trimmed.match(/^([A-Za-z0-9_-]+)\s*:\s*(.*)$/);
    if (!kv) {
      continue;
    }

    const key = kv[1];
    let value = kv[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (value === 'true') {
      value = true;
    } else if (value === 'false') {
      value = false;
    } else if (/^-?\d+(\.\d+)?$/.test(value)) {
      value = Number(value);
    }

    frontMatter[key] = value;
  }

  return {frontMatter, body: raw.slice(match[0].length)};
}

function extractTitle({frontMatter, body, fallback}) {
  if (frontMatter.title) {
    return String(frontMatter.title).trim();
  }

  const headingMatch = body.match(/^#\s+(.+)$/m);
  if (headingMatch) {
    return headingMatch[1].trim();
  }

  return fallback;
}

async function listDocFiles(dir) {
  const entries = await fs.readdir(dir, {withFileTypes: true});
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listDocFiles(fullPath)));
      continue;
    }

    if (entry.isFile() && /\.(md|mdx)$/i.test(entry.name)) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function buildDocId({docsRoot, filePath, frontMatter}) {
  const relPath = path.relative(docsRoot, filePath);
  const relNoExt = relPath.replace(/\.(md|mdx)$/i, '');
  const relDir = path.dirname(relNoExt);
  const dirName = relDir === '.' ? '' : relDir.split(path.sep).join('/');

  if (frontMatter.id) {
    return dirName ? `${dirName}/${frontMatter.id}` : String(frontMatter.id);
  }

  return relNoExt.split(path.sep).join('/');
}

function buildDocRoute({docId, slug, baseUrl, routeBasePath}) {
  if (slug && typeof slug === 'string' && slug.startsWith('/')) {
    return normalizeUrlPath(baseUrl, slug);
  }

  const docDir = docId.split('/').slice(0, -1).join('/');
  const docSlug = slug && typeof slug === 'string' ? slug : docId;
  const routeTarget = slug && docDir ? `${docDir}/${docSlug}` : docSlug;

  return normalizeUrlPath(baseUrl, routeBasePath, routeTarget);
}

function collectDocIds(items, docMap, bucket) {
  for (const item of items) {
    if (typeof item === 'string') {
      bucket.push(item);
      continue;
    }

    if (!item || typeof item !== 'object') {
      continue;
    }

    if (item.type === 'doc' && item.id) {
      bucket.push(item.id);
      continue;
    }

    if (item.type === 'category') {
      if (item.link && item.link.type === 'doc' && item.link.id) {
        bucket.push(item.link.id);
      }

      if (Array.isArray(item.items)) {
        collectDocIds(item.items, docMap, bucket);
      }

      continue;
    }

    if (item.type === 'autogenerated' && item.dirName) {
      const dirPrefix = String(item.dirName).replace(/\/+$/g, '');
      const matches = [...docMap.values()].filter((doc) => {
        return doc.docId === dirPrefix || doc.docId.startsWith(`${dirPrefix}/`);
      });

      matches.sort((a, b) => {
        const posA = a.sidebarPosition ?? Number.POSITIVE_INFINITY;
        const posB = b.sidebarPosition ?? Number.POSITIVE_INFINITY;
        if (posA !== posB) {
          return posA - posB;
        }

        return a.docId.localeCompare(b.docId);
      });

      for (const doc of matches) {
        bucket.push(doc.docId);
      }
    }
  }
}

async function loadDocsConfig() {
  const configPath = path.join(DOCS_PROJECT_ROOT, 'docusaurus.config.js');
  const raw = await fs.readFile(configPath, 'utf8');
  const docsBlockMatch = raw.match(/docs:\s*{([\s\S]*?)},\s*blog:/);
  const docsBlock = docsBlockMatch ? docsBlockMatch[1] : raw;

  const readOption = (block, key) => {
    const match = block.match(new RegExp(`${key}\\s*:\\s*['"]([^'"]+)['"]`));
    return match ? match[1] : null;
  };

  return {
    siteUrl: readOption(raw, 'url') || DEFAULT_DOCS_HOST,
    baseUrl: readOption(raw, 'baseUrl') || '/',
    routeBasePath: readOption(docsBlock, 'routeBasePath') || 'docs',
    docsPath: readOption(docsBlock, 'path') || 'docs',
    sidebarPath: readOption(docsBlock, 'sidebarPath') || './sidebars.js',
  };
}

async function loadSidebars(sidebarPath) {
  const raw = await fs.readFile(sidebarPath, 'utf8');
  const transformed = raw.replace(/export default sidebars;\s*$/, 'module.exports = sidebars;\n');
  const context = {
    module: {exports: {}},
    exports: {},
    require,
    __dirname: path.dirname(sidebarPath),
    __filename: sidebarPath,
  };

  vm.runInNewContext(transformed, context, {filename: sidebarPath});
  return context.module.exports;
}

async function generateKnowledgeBaseText() {
  const config = await loadDocsConfig();
  const docsRoot = path.resolve(DOCS_PROJECT_ROOT, config.docsPath);
  const sidebarPath = path.resolve(DOCS_PROJECT_ROOT, config.sidebarPath);
  const sidebars = await loadSidebars(sidebarPath);
  const docFiles = await listDocFiles(docsRoot);
  const docMap = new Map();

  for (const filePath of docFiles) {
    const raw = await fs.readFile(filePath, 'utf8');
    const {frontMatter, body} = parseFrontMatter(raw);

    if (frontMatter.draft === true) {
      continue;
    }

    const docId = buildDocId({docsRoot, filePath, frontMatter});
    if (docMap.has(docId)) {
      throw new Error(`Duplicate doc id detected: ${docId}`);
    }

    docMap.set(docId, {
      docId,
      filePath,
      title: extractTitle({
        frontMatter,
        body,
        fallback: path.basename(filePath, path.extname(filePath)),
      }),
      slug: frontMatter.slug ? String(frontMatter.slug) : null,
      body: body.trim(),
      sidebarPosition:
        typeof frontMatter.sidebar_position === 'number'
          ? frontMatter.sidebar_position
          : null,
    });
  }

  const orderedDocIds = [];
  for (const sidebar of Object.values(sidebars)) {
    collectDocIds(sidebar, docMap, orderedDocIds);
  }

  const seen = new Set();
  const sections = [];
  for (const docId of orderedDocIds) {
    if (seen.has(docId)) {
      continue;
    }

    seen.add(docId);
    const doc = docMap.get(docId);
    if (!doc) {
      console.warn(`Sidebar entry not found in docs: ${docId}`);
      continue;
    }

    const route = buildDocRoute({
      docId: doc.docId,
      slug: doc.slug,
      baseUrl: config.baseUrl,
      routeBasePath: config.routeBasePath,
    });
    const sourceUrl = new URL(route, config.siteUrl).toString();

    sections.push(
      ['SOURCE', sourceUrl, '', 'TITLE', doc.title, '', 'CONTENT', doc.body, ''].join(
        '\n'
      )
    );
  }

  if (sections.length === 0) {
    throw new Error('No docs were processed from sidebars.');
  }

  const sources = sections
    .map((section) => section.split('\n')[1])
    .filter(Boolean);
  const expectedOrigin = new URL(config.siteUrl).origin;
  const sourceSet = new Set(sources);

  if (sources.some((source) => new URL(source).origin !== expectedOrigin)) {
    throw new Error(`Invalid SOURCE URL found outside ${expectedOrigin}.`);
  }

  if (sourceSet.size !== sources.length) {
    throw new Error('Duplicate SOURCE URLs found in output.');
  }

  return {
    outputPath: OUTPUT_PATH,
    sectionCount: sections.length,
    text: sections.join('\n'),
  };
}

async function buildKnowledgeBase({check = false} = {}) {
  const {outputPath, sectionCount, text} = await generateKnowledgeBaseText();

  if (check) {
    let existingText = null;
    try {
      existingText = await fs.readFile(outputPath, 'utf8');
    } catch (error) {
      if (error.code !== 'ENOENT') {
        throw error;
      }
    }

    if (existingText !== text) {
      throw new Error(`Knowledge base output is not current: ${outputPath}`);
    }

    console.log(`Knowledge base is current (${sectionCount} doc(s)).`);
    return {outputPath, sectionCount, text};
  }

  await fs.writeFile(outputPath, text, 'utf8');
  console.log(`Processed ${sectionCount} doc(s).`);
  console.log(`Output: ${outputPath}`);

  return {outputPath, sectionCount, text};
}

if (require.main === module) {
  buildKnowledgeBase({check: process.argv.includes('--check')}).catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = {
  OUTPUT_PATH,
  buildKnowledgeBase,
  generateKnowledgeBaseText,
};
